# Generated by Django 2.2.3 on 2019-07-03 16:46

import api.managers.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_region', models.CharField(blank=True, max_length=100, verbose_name='shipping_region')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('credit_card', models.CharField(blank=True, max_length=100, verbose_name='credit_card')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='address_1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='address_2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('postal_code', models.CharField(blank=True, max_length=100, verbose_name='postal_code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('day_phone', models.CharField(blank=True, max_length=100, verbose_name='day_phone')),
                ('eve_phone', models.CharField(blank=True, max_length=100, verbose_name='eve_phone')),
                ('mob_phone', models.CharField(blank=True, max_length=100, verbose_name='mob_phone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('shipping_region', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ShippingRegion')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
            managers=[
                ('objects', api.managers.user.UserManager()),
            ],
        ),
    ]
