# Generated by Django 2.2.3 on 2019-07-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190703_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping_region',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ShippingRegion'),
        ),
    ]
