# Generated by Django 2.2.3 on 2019-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190703_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='address one'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='address two'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='day_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='day phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='eve_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='evening phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mob_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='postal code'),
        ),
    ]
