# Generated by Django 2.2.3 on 2019-07-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190703_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingregion',
            table='shipping_region',
        ),
    ]
